{% set version = '0.2.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bayestestr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bayestestR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bayestestR/bayestestR_{{ version }}.tar.gz
  sha256: a941ca187a924feb2a2c6a6b22c77e912336fa72420b582cd496739829292627

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-insight >=0.3.0
  run:
    - r-base
    - r-insight >=0.3.0

test:
  commands:
    - $R -e "library('bayestestR')"           # [not win]
    - "\"%R%\" -e \"library('bayestestR')\""  # [win]

about:
  home: https://github.com/easystats/bayestestR
  license: GPL-3
  summary: Provides utilities to describe posterior distributions and Bayesian models. It includes
    point-estimates such as Maximum A Posteriori (MAP), measures of dispersion (Highest
    Density Interval - HDI; Kruschke, 2015 <doi:10.1016/C2012-0-00477-2>) and indices
    used for null-hypothesis testing (such as ROPE percentage, pd and Bayes factors).
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: bayestestR
# Type: Package
# Title: Understand and Describe Bayesian Models and Posterior Distributions
# Version: 0.2.2
# Authors@R: c( person("Dominique",  "Makowski",  email = "dom.makowski@gmail.com", role = c("aut", "cre"),  comment = c(ORCID = "0000-0001-5375-9967")), person("Daniel",  "Ludecke",  role = c("aut"),  email = "d.luedecke@uke.de",  comment = c(ORCID = "0000-0002-8895-3206")), person("Mattan S.",  "Ben-Shachar",  role = c("aut"),  email = "matanshm@post.bgu.ac.il",  comment = c(ORCID = "0000-0002-4287-4801")), person("Michael D.",  "Wilson",  role = c("aut"),  email = "michael.d.wilson@curtin.edu.au",  comment = c(ORCID = "0000-0003-4143-7308")) )
# Maintainer: Dominique Makowski <dom.makowski@gmail.com>
# URL: https://github.com/easystats/bayestestR
# BugReports: https://github.com/easystats/bayestestR/issues
# Description: Provides utilities to describe posterior distributions and Bayesian models. It includes point-estimates such as Maximum A Posteriori (MAP), measures of dispersion (Highest Density Interval - HDI; Kruschke, 2015 <doi:10.1016/C2012-0-00477-2>) and indices used for null-hypothesis testing (such as ROPE percentage, pd and Bayes factors).
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# Depends: R (>= 3.0), stats, methods, utils
# Imports: insight (>= 0.3.0)
# Suggests: BayesFactor, bridgesampling, brms, broom, covr, dplyr, emmeans, tidyr, GGally, ggplot2, ggridges, KernSmooth, knitr, lme4, logspline, see, rmarkdown, rstan, rstanarm, stringr, testthat
# RoxygenNote: 6.1.1
# Language: en-GB
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-06-20 12:12:50 UTC; Dom
# Author: Dominique Makowski [aut, cre] (<https://orcid.org/0000-0001-5375-9967>), Daniel Ludecke [aut] (<https://orcid.org/0000-0002-8895-3206>), Mattan S. Ben-Shachar [aut] (<https://orcid.org/0000-0002-4287-4801>), Michael D. Wilson [aut] (<https://orcid.org/0000-0003-4143-7308>)
# Repository: CRAN
# Date/Publication: 2019-06-20 12:50:03 UTC
