{% set version = "0.13.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bayestestr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bayestestR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bayestestR/bayestestR_{{ version }}.tar.gz
  sha256: 206905f5e9ac82c9a6d1c41008713d952b71f8fbeee7a732c975518c50fda1a4

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-datawizard
    - r-insight >=0.14.1
  run:
    - r-base
    - r-datawizard
    - r-insight >=0.14.1

test:
  commands:
    - $R -e "library('bayestestR')"           # [not win]
    - "\"%R%\" -e \"library('bayestestR')\""  # [win]

about:
  home: https://github.com/easystats/bayestestR
  license: GPL-3.0-only
  summary: Provides utilities to describe posterior distributions and Bayesian models. It includes point-estimates such as Maximum A Posteriori (MAP), measures of dispersion (Highest Density Interval - HDI; Kruschke, 2015 <doi:10.1016/C2012-0-00477-2>) and indices used for null-hypothesis testing (such as ROPE percentage,
    pd and Bayes factors).
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: bayestestR
# Type: Package
# Title: Understand and Describe Bayesian Models and Posterior Distributions
# Version: 0.3.0
# Authors@R: c( person("Dominique",  "Makowski",  email = "dom.makowski@gmail.com", role = c("aut", "cre"),  comment = c(ORCID = "0000-0001-5375-9967")), person("Daniel",  "Ldecke",  role = c("aut"),  email = "d.luedecke@uke.de",  comment = c(ORCID = "0000-0002-8895-3206")), person("Mattan S.",  "Ben-Shachar",  role = c("aut"),  email = "matanshm@post.bgu.ac.il",  comment = c(ORCID = "0000-0002-4287-4801")), person("Michael D.",  "Wilson",  role = c("aut"),  email = "michael.d.wilson@curtin.edu.au",  comment = c(ORCID = "0000-0003-4143-7308")), person("Paul-Christian",  "Brkner",  role = c("rev"),  email = "paul.buerkner@gmail.com"), person("Tristan",  "Mahr",  role = c("rev"), email = "tristan.mahr@wisc.edu", comment = c(ORCID = "0000-0002-8890-5116")), person("Henrik", "Singmann", role = c("ctb"), email = "singmann@gmail.com", comment = c(ORCID = "0000-0002-4842-3657")), person("Quentin F.", "Gronau", role = c("ctb"), comment = c(ORCID = "0000-0001-5510-6943")) )
# Maintainer: Dominique Makowski <dom.makowski@gmail.com>
# URL: https://github.com/easystats/bayestestR
# BugReports: https://github.com/easystats/bayestestR/issues
# Description: Provides utilities to describe posterior distributions and Bayesian models. It includes point-estimates such as Maximum A Posteriori (MAP), measures of dispersion (Highest Density Interval - HDI; Kruschke, 2015 <doi:10.1016/C2012-0-00477-2>) and indices used for null-hypothesis testing (such as ROPE percentage, pd and Bayes factors).
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# Depends: R (>= 3.0)
# Imports: insight (>= 0.5.0), methods, stats, utils
# Suggests: BayesFactor, bridgesampling, brms, broom, covr, dplyr, emmeans, GGally, ggplot2, ggridges, KernSmooth, knitr, lme4, logspline, performance, rmarkdown, rstan, rstanarm, see, stringr, testthat, tidyr
# RoxygenNote: 6.1.1
# Language: en-GB
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-09-22 05:23:17 UTC; Dom
# Author: Dominique Makowski [aut, cre] (<https://orcid.org/0000-0001-5375-9967>), Daniel Ldecke [aut] (<https://orcid.org/0000-0002-8895-3206>), Mattan S. Ben-Shachar [aut] (<https://orcid.org/0000-0002-4287-4801>), Michael D. Wilson [aut] (<https://orcid.org/0000-0003-4143-7308>), Paul-Christian Brkner [rev], Tristan Mahr [rev] (<https://orcid.org/0000-0002-8890-5116>), Henrik Singmann [ctb] (<https://orcid.org/0000-0002-4842-3657>), Quentin F. Gronau [ctb] (<https://orcid.org/0000-0001-5510-6943>)
# Repository: CRAN
# Date/Publication: 2019-09-22 16:30:05 UTC
