appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: XSbILrVnyyiQzCWf+igTk2UqPG7HcsxMnN/YVNN6gYh6PSg6GNoryv9UukrLa6Dk9GvhrDcfh6hQcLxXJ/oobYcLtDYBVy9/V/7sRVBUeYIp0qJwuFljLhzJd5bejPr5wsXcHW1BsubY26IxJpJlpK9aalWusepsBEKXYl2qyzN/o4GU4rZpZB9nWFVQORCVLzlFASQxC6HYNfaW6aeZoPFbXdaym59Kay6owmHQ8MpNYKpa1uOd8f7paytqIwDnJGMImwkmZLeT0NHzs/JkLbsqfmX3nWSZlo1lEFz6vvkN7T7Tw0Swd91ouHDUdoj4sKqFTL4IjuBi1exxelM4+XrMwS5TogzfexUGGVPUZvrpv2DBM4wquz4UZeVO3gc7lCeomPUhZz0xrJsFdSJiLRKaDLG8a0SzjxCL27fF079Dpww8lgKpVOQe7WKTYEzA4V+QQBzfNYLDdY6nga0U4jsR+CM1g68Qo+N0aYGO779/AY8l/bAd//SyY2sLXL48+f1pj2bbRlKAH+o59mLnYvAFMLWCoo2OweTlI1aJF6108EjdBLk2wInI+DbCcNlqNVl/jWXPe7XX8jMPnZxIVyL7ER9wH2A5oImZ/WBHNRSnV3aZCqZfGjjRxNoTE8+PDjO0c0sDJ7WdesQBM/iLimWkpU1YSMXsweteMi+AdQU=}
bot:
  automerge: true
